GET http://localhost:3001/players/

###

POST http://localhost:3001/players/

###

GET http://localhost:3001/players/5/

###

PUT http://localhost:3001/players/7/

###

DELETE http://localhost:3001/players/1/

